apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  volumeName: pv-data
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
